### ISSUE TITLE
proposition: indent object

### ISSUE THREAD

**Issue by amigrave** [bps/vim-textobj-python#11]
Maybe including this indentation zones as a text object would make your pllugin more complete.

https://github.com/michaeljsmith/vim-indent-object

**Note** I don't know if textobj-user allows to create such an object.

**Comment by bps** [comment]
Is there anything preventing both objects being used in parallel?

**Comment by amigrave** [comment]
My apologizes, it must be another plugin conflicting because when I only leave vim-textobj-user, "-python and vim-indent-object, it's ok.
Sorry for the noise.
