### ISSUE TITLE
y(a|i)f isn't retaining place in function

### ISSUE THREAD

**Issue by lee-kagiso** [bps/vim-textobj-python#16]
If I go to the middle of a function body, type `yif`, the cursor then jumps to the top of the function (the line with the def keyword). 

Is there a reason for this, shouldn't the cursor stay put?

**Comment by bps** [comment]
I believe this is the same behavior as the built-in text objects. If I'm in the middle of a C block and type `yi}`, the contents of the block are yanked and the cursor is moved to the beginning of the block.

I get why you'd often want the cursor to stay put, but I'd like to maintain consistency. Double backtick or `C-o` might be a decent workaround.

Let me know if I'm mistaken about the built-in behavior.

**Comment by lee-kagiso** [comment]
Yeah I see, never really noticed that before
